In [142]:
import pandas as pd
import geonamescache
df = pd.read_csv('ParsingNewsHeadlines.csv')
gnc = geonamescache.GeonamesCache()
arrlat = []
arrlong = []
arrcountry = []
for ind in df.index:
    if (df['cities'][ind] == "NaN" or gnc.get_cities_by_name(df['cities'][ind]) == []):
        arrlat.append("NaN")
        arrlong.append("NaN")
        arrcountry.append("NaN")
    else: 
        city_thing = [k for k in gnc.get_cities_by_name(df['cities'][ind])[0]]
        #print (city_thing)
        max1 = 0;
        index = 0;
        for i in range(len(city_thing)):
            thing = city_thing[i]
            if (max1 <= gnc.get_cities_by_name(df['cities'][ind])[i][thing]['population']):
                max1 = gnc.get_cities_by_name(df['cities'][ind])[i][thing]['population']
                index = i
        
        city_thing = city_thing[index]
        city_thing = str(city_thing)
        #print(city_thing)
        arrlat.append(gnc.get_cities_by_name(df['cities'][ind])[index][city_thing]['latitude'])
        arrlong.append(gnc.get_cities_by_name(df['cities'][ind])[index][city_thing]['longitude'])
        arrcountry.append(gnc.get_cities_by_name(df['cities'][ind])[index][city_thing]['countrycode'])
        #print(number)
df['latitude'] = arrlat
df['longitude'] = arrlong
df['countrycodes'] = arrcountry
df = df.drop('countries', 1)
df

,headline,cities,latitude,longitude,countrycodes
0,Zika Outbreak Hits Miami,Miami,25.7743,-80.1937,US
1,Could Zika Reach New York City?,New York City,40.7143,-74.006,US
2,First Case of Zika in Miami Beach,Miami Beach,25.7906,-80.13,US
3,"Mystery Virus Spreads in Recife, Brazil",Recife,-8.05389,-34.8811,BR
4,Dallas man comes down with case of Zika,Dallas,32.7831,-96.8067,US
5,Trinidad confirms first Zika case,Trinidad,-14.8333,-64.9,BO
6,Zika Concerns are Spreading in Houston,Houston,29.7633,-95.3633,US
7,Geneve Scientists Battle to Find Cure,NaN,NaN,NaN,NaN
8,The CDC in Atlanta is Growing Worried,Atlanta,33.749,-84.388,US
9,Zika Infested Monkeys in Sao Paulo,NaN,NaN,NaN,NaN
10,Brownsville teen contracts Zika virus,Brownsville,25.8218,-80.2412,US
11,Mosquito control efforts in St. Louis take new...,NaN,NaN,NaN,NaN
12,San Juan reports 1st U.S. Zika-related death a...,San Juan,-31.5375,-68.5364,AR
13,"Flu outbreak in Galveston, Texas",Galveston,29.3013,-94.7977,US
14,Zika alert â€“ Manila now threatened,Manila,14.6042,120.982,PH
15,Zika afflicts 7 in Iloilo City,Iloilo,10.6969,122.564,PH
16,New Los Angeles Hairstyle goes Viral,Los Angeles,34.0522,-118.244,US
17,Louisiana Zika cases up to 26,NaN,NaN,NaN,NaN
18,Orlando volunteers aid Zika research,Orlando,28.5383,-81.3792,US
19,Zika infects pregnant woman in Cebu,NaN,NaN,NaN,NaN
20,Chicago's First Zika Case Confirmed,NaN,NaN,NaN,NaN
21,Tampa Bay Area Zika Case Count Climbs,Tampa,27.9475,-82.4584,US
22,"Bad Water Leads to Sickness in Flint, Michigan",Flint,53.2449,-3.13231,GB
23,Baltimore plans for Zika virus,Baltimore,39.2904,-76.6122,US
24,London Health Unit Tracks Mad Cow Disease,London,42.9834,-81.233,CA
25,Zika cases in Vietnam's Ho Chi Minh City surge,Ho Chi Minh City,10.823,106.63,VN
26,Philadelphia experts track pandemic,Philadelphia,39.9523,-75.1638,US
27,Flu season hits Boston,Boston,52.9763,-0.02664,GB
28,Scientists in Paris to look for answers,Paris,48.8534,2.3488,FR
29,Key Zika Findings in San Diego Institute,San Diego,9.89898,-84.0029,CR
...,...,...,...,...,...
620,How to Avoid Chikungunya in Hampton,Hampton,51.4133,-0.36701,GB
621,Zika Reported in Sao Jose,NaN,NaN,NaN,NaN
622,Case of Norovirus Reported in Stratford,Stratford,43.3668,-80.9497,CA
623,How to Avoid Hepatitis E in South Bend,South Bend,41.6834,-86.25,US
624,Hepatitis C Outbreak in Bethlehem,Bethlehem,31.7049,35.2038,PS
625,Davenport is infested with Dengue,Davenport,41.5236,-90.5776,US
626,Rumors about Swine Flu spreading in Suzhou hav...,Suzhou,33.6361,116.979,CN
627,Malaria Vaccine is now Required in Elyria,Elyria,41.3684,-82.1077,US
628,Zika case reported in Antioquia,NaN,NaN,NaN,NaN
629,Case of Swine Flu Reported in Tbilisi,Tbilisi,41.6941,44.8337,GE
630,Chikungunya has not Left Pismo Beach,NaN,NaN,NaN,NaN
631,Zika spreads to La Joya,NaN,NaN,NaN,NaN
632,Influenza Keeps Spreading in Suffolk,Suffolk,36.7284,-76.585,US
633,More people in Allentown are infected with Chl...,Allentown,40.6084,-75.4902,US
634,Mad Cow Disease re-emerges in Bedford,Bedford,52.1346,-0.46632,GB
635,Authorities are Worried about the Spread of He...,Yiwu,29.3151,120.077,CN
636,Zika Outbreak in Yurimaguas,Yurimaguas,-5.90181,-76.1223,PE
637,Dengue Outbreak in Easton,Easton,38.7743,-76.0763,US
638,Varicella has Arrived in Milton,Milton,43.5168,-79.8829,CA
639,New medicine wipes out Meningitis in Sevilla,Sevilla,4.26425,-75.9309,CO
640,Authorities are Worried about the Spread of Va...,Clovis,36.8252,-119.703,US
641,More Zika patients reported in Fort Worth,Fort Worth,32.7254,-97.3208,US
642,Zika symptoms spotted in Boynton Beach,Boynton Beach,26.5253,-80.0664,US
643,Outbreak of Zika in Portoviejo,Portoviejo,-1.05458,-80.4544,EC
644,Influenza Exposure in Muscat,Muscat,23.5841,58.4078,OM
645,Rumors about Rabies spreading in Jerusalem hav...,Jerusalem,31.769,35.2163,IL
646,More Zika patients reported in Indang,Indang,14.1953,120.877,PH
647,Suva authorities confirmed the spread of Rotav...,Suva,-18.1416,178.441,FJ
648,More Zika patients reported in Bella Vista,Bella Vista,-27.0342,-65.302,AR
649,Zika Outbreak in Wichita Falls,Wichita Falls,33.9137,-98.4934,US